[2025-05-20T10:24:53.357+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T10:24:53.363+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.spark_etl scheduled__2025-05-19T16:00:00+00:00 [queued]>
[2025-05-20T10:24:53.366+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.spark_etl scheduled__2025-05-19T16:00:00+00:00 [queued]>
[2025-05-20T10:24:53.366+0000] {taskinstance.py:2865} INFO - Starting attempt 22 of 24
[2025-05-20T10:24:53.370+0000] {taskinstance.py:2888} INFO - Executing <Task(SSHOperator): spark_etl> on 2025-05-19 16:00:00+00:00
[2025-05-20T10:24:53.372+0000] {standard_task_runner.py:72} INFO - Started process 226 to run task
[2025-05-20T10:24:53.373+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_minio_to_spark', 'spark_etl', 'scheduled__2025-05-19T16:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/testlog_ml.py', '--cfg-path', '/tmp/tmpp4i7etyw']
[2025-05-20T10:24:53.374+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask spark_etl
[2025-05-20T10:24:53.460+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_minio_to_spark.spark_etl scheduled__2025-05-19T16:00:00+00:00 [running]> on host 6a89a243c286
[2025-05-20T10:24:53.481+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_minio_to_spark' AIRFLOW_CTX_TASK_ID='spark_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='22' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T16:00:00+00:00'
[2025-05-20T10:24:53.481+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-20T10:24:53.485+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-05-20T10:24:53.488+0000] {base.py:84} INFO - Retrieving connection 'local_ssh'
[2025-05-20T10:24:53.488+0000] {ssh.py:309} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-05-20T10:24:53.535+0000] {transport.py:1923} INFO - Connected (version 2.0, client OpenSSH_9.8)
[2025-05-20T10:24:53.739+0000] {transport.py:1923} INFO - Authentication (password) successful!
[2025-05-20T10:24:53.741+0000] {ssh.py:493} INFO - Running command: sh -c "/Users/jeongmieun/.pyenv/versions/airminio/bin/python /Users/jeongmieun/test/docker_***/dags/testlog_ml_spark.py"
[2025-05-20T10:24:54.440+0000] {ssh.py:544} WARNING - 25/05/20 19:24:54 WARN Utils: Your hostname, jeongmieun-ui-MacBookAir.local resolves to a loopback address: 127.0.0.1; using 172.16.24.224 instead (on interface en0)
[2025-05-20T10:24:54.441+0000] {ssh.py:544} WARNING - 25/05/20 19:24:54 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-05-20T10:24:54.602+0000] {ssh.py:544} WARNING - 25/05/20 19:24:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-20T10:24:54.692+0000] {ssh.py:544} WARNING - Setting default log level to "WARN".
[2025-05-20T10:24:54.693+0000] {ssh.py:544} WARNING - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-20T10:24:55.006+0000] {ssh.py:544} WARNING - 25/05/20 19:24:55 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-05-20T10:24:55.009+0000] {ssh.py:544} WARNING - 25/05/20 19:24:55 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-05-20T10:24:55.010+0000] {ssh.py:544} WARNING - 25/05/20 19:24:55 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2025-05-20T10:24:55.010+0000] {ssh.py:544} WARNING - 25/05/20 19:24:55 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2025-05-20T10:24:55.011+0000] {ssh.py:544} WARNING - 25/05/20 19:24:55 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2025-05-20T10:24:55.676+0000] {ssh.py:544} WARNING - 25/05/20 19:24:55 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-05-20T10:25:05.715+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 175, in run_ssh_client_command
    exit_status, agg_stdout, agg_stderr = self.hook.exec_ssh_client_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/hooks/ssh.py", line 564, in exec_ssh_client_command
    raise AirflowException("SSH command timed out")
airflow.exceptions.AirflowException: SSH command timed out
[2025-05-20T10:25:05.721+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_minio_to_spark, task_id=spark_etl, run_id=scheduled__2025-05-19T16:00:00+00:00, execution_date=20250519T160000, start_date=20250520T102453, end_date=20250520T102505
[2025-05-20T10:25:05.732+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-20T10:25:05.733+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task spark_etl (SSH command timed out; 226)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 175, in run_ssh_client_command
    exit_status, agg_stdout, agg_stderr = self.hook.exec_ssh_client_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/hooks/ssh.py", line 564, in exec_ssh_client_command
    raise AirflowException("SSH command timed out")
airflow.exceptions.AirflowException: SSH command timed out
[2025-05-20T10:25:05.746+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T10:25:05.843+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T10:25:05.845+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
