[2025-05-20T03:18:41.826+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T03:18:41.832+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-20T01:00:00+00:00 [queued]>
[2025-05-20T03:18:41.835+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-20T01:00:00+00:00 [queued]>
[2025-05-20T03:18:41.835+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-20T03:18:41.839+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): kafka_consumer> on 2025-05-20 01:00:00+00:00
[2025-05-20T03:18:41.841+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2025-05-20T03:18:41.843+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_minio_to_spark', 'kafka_consumer', 'scheduled__2025-05-20T01:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/testlog_ml.py', '--cfg-path', '/tmp/tmp2h5g6lst']
[2025-05-20T03:18:41.844+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask kafka_consumer
[2025-05-20T03:18:41.862+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-20T01:00:00+00:00 [running]> on host 9a4735d46559
[2025-05-20T03:18:41.886+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_minio_to_spark' AIRFLOW_CTX_TASK_ID='kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-20T01:00:00+00:00'
[2025-05-20T03:18:41.887+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-20T03:18:41.893+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-20T03:18:41.897+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <checking_api_versions_recv> [IPv4 ('192.168.65.254', 9092)]>: Broker version identified as 2.6
[2025-05-20T03:18:41.897+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Connection complete.
[2025-05-20T03:18:41.898+0000] {subscription_state.py:177} INFO - Updating subscribed topics to: ('userlog',)
[2025-05-20T03:18:41.898+0000] {logging_mixin.py:190} INFO - âœ… consumer started, waiting for messages....
[2025-05-20T03:18:41.901+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: connecting to 172.16.24.224:9092 [('172.16.24.224', 9092) IPv4]
[2025-05-20T03:18:42.004+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Connection complete.
[2025-05-20T03:18:42.005+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. 
[2025-05-20T03:18:42.109+0000] {cluster.py:400} INFO - Coordinator for group/userlog is ('coordinator-1', '172.16.24.224', 9092, None)
[2025-05-20T03:18:42.109+0000] {base.py:769} INFO - Discovered coordinator coordinator-1 for group userlog
[2025-05-20T03:18:42.109+0000] {base.py:820} INFO - Starting new heartbeat thread
[2025-05-20T03:18:42.110+0000] {consumer.py:362} INFO - Revoking previously assigned partitions () for group userlog
[2025-05-20T03:18:42.111+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: connecting to 172.16.24.224:9092 [('172.16.24.224', 9092) IPv4]
[2025-05-20T03:18:42.214+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Connection complete.
[2025-05-20T03:18:42.319+0000] {base.py:524} INFO - (Re-)joining group userlog
[2025-05-20T03:18:42.327+0000] {base.py:524} INFO - (Re-)joining group userlog
[2025-05-20T03:18:45.335+0000] {base.py:587} INFO - Elected group leader -- performing partition assignments using range
[2025-05-20T03:18:45.344+0000] {base.py:401} INFO - Successfully joined group userlog with generation 1
[2025-05-20T03:18:45.346+0000] {subscription_state.py:246} INFO - Updated partition assignment: [('userlog', 0)]
[2025-05-20T03:18:45.347+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('userlog', 0),) for group userlog
[2025-05-20T03:18:45.368+0000] {fetcher.py:413} INFO - Resetting offset for partition ('userlog', 0) to offset 0.
[2025-05-20T03:18:45.414+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testlog_ml.py", line 97, in kafka_consumer
    writer.writerow({key: event[key] for key in fieldnames})
  File "/opt/airflow/dags/testlog_ml.py", line 97, in <dictcomp>
    writer.writerow({key: event[key] for key in fieldnames})
KeyError: 'review'
[2025-05-20T03:18:45.421+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_minio_to_spark, task_id=kafka_consumer, run_id=scheduled__2025-05-20T01:00:00+00:00, execution_date=20250520T010000, start_date=20250520T031841, end_date=20250520T031845
[2025-05-20T03:18:45.430+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-20T03:18:45.430+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 109 for task kafka_consumer ('review'; 118)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testlog_ml.py", line 97, in kafka_consumer
    writer.writerow({key: event[key] for key in fieldnames})
  File "/opt/airflow/dags/testlog_ml.py", line 97, in <dictcomp>
    writer.writerow({key: event[key] for key in fieldnames})
KeyError: 'review'
[2025-05-20T03:18:45.471+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T03:18:45.479+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T03:18:45.480+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
