[2025-05-22T07:41:01.541+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-22T07:41:01.545+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-21T16:00:00+00:00 [queued]>
[2025-05-22T07:41:01.548+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-21T16:00:00+00:00 [queued]>
[2025-05-22T07:41:01.548+0000] {taskinstance.py:2865} INFO - Starting attempt 10 of 10
[2025-05-22T07:41:01.552+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): kafka_consumer> on 2025-05-21 16:00:00+00:00
[2025-05-22T07:41:01.554+0000] {standard_task_runner.py:72} INFO - Started process 1598 to run task
[2025-05-22T07:41:01.555+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_minio_to_spark', 'kafka_consumer', 'scheduled__2025-05-21T16:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/testlog_ml.py', '--cfg-path', '/tmp/tmpzmrn5_ee']
[2025-05-22T07:41:01.556+0000] {standard_task_runner.py:105} INFO - Job 219: Subtask kafka_consumer
[2025-05-22T07:41:01.572+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_minio_to_spark.kafka_consumer scheduled__2025-05-21T16:00:00+00:00 [running]> on host d1f65538eb5f
[2025-05-22T07:41:01.595+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_minio_to_spark' AIRFLOW_CTX_TASK_ID='kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T16:00:00+00:00'
[2025-05-22T07:41:01.595+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-22T07:41:01.602+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-22T07:41:01.603+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-05-22T07:41:01.603+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Connection complete.
[2025-05-22T07:41:01.725+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-05-22T07:41:01.725+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-05-22T07:41:01.726+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('userlog',)
[2025-05-22T07:41:01.726+0000] {logging_mixin.py:190} INFO - ‚úÖ consumer started, waiting for messages....
[2025-05-22T07:41:01.727+0000] {cluster.py:371} INFO - Group coordinator for ttest is ('coordinator-1', '172.16.24.224', 9092, None)
[2025-05-22T07:41:01.727+0000] {base.py:693} INFO - Discovered coordinator coordinator-1 for group ttest
[2025-05-22T07:41:01.728+0000] {base.py:741} INFO - Starting new heartbeat thread
[2025-05-22T07:41:01.728+0000] {consumer.py:348} INFO - Revoking previously assigned partitions () for group ttest
[2025-05-22T07:41:01.729+0000] {conn.py:380} INFO - <BrokerConnection node_id=coordinator-1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: connecting to 172.16.24.224:9092 [('172.16.24.224', 9092) IPv4]
[2025-05-22T07:41:01.830+0000] {conn.py:410} INFO - <BrokerConnection node_id=coordinator-1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: Connection complete.
[2025-05-22T07:41:01.832+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. 
[2025-05-22T07:41:01.935+0000] {base.py:450} INFO - (Re-)joining group ttest
[2025-05-22T07:41:04.941+0000] {base.py:521} INFO - Elected group leader -- performing partition assignments using range
[2025-05-22T07:41:04.944+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: connecting to 172.16.24.224:9092 [('172.16.24.224', 9092) IPv4]
[2025-05-22T07:41:04.947+0000] {base.py:335} INFO - Successfully joined group ttest with generation 1
[2025-05-22T07:41:04.948+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('userlog', 0), ('userlog', 1), ('userlog', 2), ('userlog', 3), ('userlog', 4), ('userlog', 5), ('userlog', 6), ('userlog', 7), ('userlog', 8), ('userlog', 9), ('userlog', 10), ('userlog', 11)]
[2025-05-22T07:41:04.949+0000] {consumer.py:245} INFO - Setting newly assigned partitions (('userlog', 6), ('userlog', 2), ('userlog', 5), ('userlog', 8), ('userlog', 11), ('userlog', 1), ('userlog', 7), ('userlog', 4), ('userlog', 10), ('userlog', 0), ('userlog', 3), ('userlog', 9)) for group ttest
[2025-05-22T07:41:04.950+0000] {conn.py:410} INFO - <BrokerConnection node_id=1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: Connection complete.
[2025-05-22T07:41:05.105+0000] {logging_mixin.py:190} INFO - *********************************
[2025-05-22T07:41:05.107+0000] {logging_mixin.py:190} INFO - *********************************
[2025-05-22T07:41:05.107+0000] {logging_mixin.py:190} INFO - üì• Received: page:main
[2025-05-22T07:41:05.108+0000] {logging_mixin.py:190} INFO - ‚ùå Failed to process message: OffsetAndMetadata.__new__() takes 3 positional arguments but 4 were given
[2025-05-22T07:41:05.108+0000] {logging_mixin.py:190} INFO - ‚ùå DAG failed due to : OffsetAndMetadata.__new__() takes 3 positional arguments but 4 were given
[2025-05-22T07:41:05.109+0000] {base.py:748} INFO - Stopping heartbeat thread
[2025-05-22T07:41:05.110+0000] {base.py:773} INFO - Leaving consumer group (ttest).
[2025-05-22T07:41:05.116+0000] {conn.py:919} INFO - <BrokerConnection node_id=coordinator-1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Closing connection. 
[2025-05-22T07:41:05.116+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Closing connection. 
[2025-05-22T07:41:05.118+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testlog_ml.py", line 152, in kafka_consumer
    raise e
  File "/opt/airflow/dags/testlog_ml.py", line 121, in kafka_consumer
    raise e
  File "/opt/airflow/dags/testlog_ml.py", line 118, in kafka_consumer
    consumer.commit(offsets={tp: OffsetAndMetadata(msg.offset + 1, None, -1)})
TypeError: OffsetAndMetadata.__new__() takes 3 positional arguments but 4 were given
[2025-05-22T07:41:05.126+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=kafka_to_minio_to_spark, task_id=kafka_consumer, run_id=scheduled__2025-05-21T16:00:00+00:00, execution_date=20250521T160000, start_date=20250522T074101, end_date=20250522T074105
[2025-05-22T07:41:05.135+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-22T07:41:05.136+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 219 for task kafka_consumer (OffsetAndMetadata.__new__() takes 3 positional arguments but 4 were given; 1598)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testlog_ml.py", line 152, in kafka_consumer
    raise e
  File "/opt/airflow/dags/testlog_ml.py", line 121, in kafka_consumer
    raise e
  File "/opt/airflow/dags/testlog_ml.py", line 118, in kafka_consumer
    consumer.commit(offsets={tp: OffsetAndMetadata(msg.offset + 1, None, -1)})
TypeError: OffsetAndMetadata.__new__() takes 3 positional arguments but 4 were given
[2025-05-22T07:41:05.167+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-22T07:41:05.185+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T07:41:05.188+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
