[2025-05-19T08:23:49.152+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T08:23:49.244+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_parquet.csv_to_parquet scheduled__2025-05-19T08:05:00+00:00 [queued]>
[2025-05-19T08:23:49.248+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_parquet.csv_to_parquet scheduled__2025-05-19T08:05:00+00:00 [queued]>
[2025-05-19T08:23:49.248+0000] {taskinstance.py:2865} INFO - Starting attempt 9 of 10
[2025-05-19T08:23:49.252+0000] {taskinstance.py:2888} INFO - Executing <Task(SSHOperator): csv_to_parquet> on 2025-05-19 08:05:00+00:00
[2025-05-19T08:23:49.255+0000] {standard_task_runner.py:72} INFO - Started process 1423 to run task
[2025-05-19T08:23:49.257+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'csv_to_parquet', 'csv_to_parquet', 'scheduled__2025-05-19T08:05:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/log_to_csv.py', '--cfg-path', '/tmp/tmp6wlemwk9']
[2025-05-19T08:23:49.258+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask csv_to_parquet
[2025-05-19T08:23:49.276+0000] {task_command.py:467} INFO - Running <TaskInstance: csv_to_parquet.csv_to_parquet scheduled__2025-05-19T08:05:00+00:00 [running]> on host 8b6a4ce3396b
[2025-05-19T08:23:49.304+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_parquet' AIRFLOW_CTX_TASK_ID='csv_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T08:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T08:05:00+00:00'
[2025-05-19T08:23:49.304+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T08:23:49.309+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-05-19T08:23:49.312+0000] {base.py:84} INFO - Retrieving connection 'local_ssh'
[2025-05-19T08:23:49.312+0000] {ssh.py:309} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-05-19T08:23:49.363+0000] {transport.py:1923} INFO - Connected (version 2.0, client OpenSSH_9.8)
[2025-05-19T08:23:49.564+0000] {transport.py:1923} INFO - Authentication (password) successful!
[2025-05-19T08:23:49.566+0000] {ssh.py:493} INFO - Running command: sh -c "/Users/jeongmieun/.pyenv/versions/airminio/bin/python /Users/jeongmieun/test/docker_***/dags/spark_to_parquet.py"
[2025-05-19T08:23:59.581+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 175, in run_ssh_client_command
    exit_status, agg_stdout, agg_stderr = self.hook.exec_ssh_client_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/hooks/ssh.py", line 564, in exec_ssh_client_command
    raise AirflowException("SSH command timed out")
airflow.exceptions.AirflowException: SSH command timed out
[2025-05-19T08:23:59.585+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_parquet, task_id=csv_to_parquet, run_id=scheduled__2025-05-19T08:05:00+00:00, execution_date=20250519T080500, start_date=20250519T082349, end_date=20250519T082359
[2025-05-19T08:23:59.593+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T08:23:59.594+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task csv_to_parquet (SSH command timed out; 1423)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 175, in run_ssh_client_command
    exit_status, agg_stdout, agg_stderr = self.hook.exec_ssh_client_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/hooks/ssh.py", line 564, in exec_ssh_client_command
    raise AirflowException("SSH command timed out")
airflow.exceptions.AirflowException: SSH command timed out
[2025-05-19T08:23:59.627+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-19T08:23:59.637+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T08:23:59.638+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
