[2025-05-20T00:05:01.242+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T00:05:01.248+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_parquet.kafka_producer scheduled__2025-05-20T00:05:00+00:00 [queued]>
[2025-05-20T00:05:01.314+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_parquet.kafka_producer scheduled__2025-05-20T00:05:00+00:00 [queued]>
[2025-05-20T00:05:01.315+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-20T00:05:01.319+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): kafka_producer> on 2025-05-20 00:05:00+00:00
[2025-05-20T00:05:01.321+0000] {standard_task_runner.py:72} INFO - Started process 5107 to run task
[2025-05-20T00:05:01.323+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'csv_to_parquet', 'kafka_producer', 'scheduled__2025-05-20T00:05:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/log_to_csv.py', '--cfg-path', '/tmp/tmpbwv4c2jf']
[2025-05-20T00:05:01.324+0000] {standard_task_runner.py:105} INFO - Job 96: Subtask kafka_producer
[2025-05-20T00:05:01.341+0000] {task_command.py:467} INFO - Running <TaskInstance: csv_to_parquet.kafka_producer scheduled__2025-05-20T00:05:00+00:00 [running]> on host 8b6a4ce3396b
[2025-05-20T00:05:01.370+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_parquet' AIRFLOW_CTX_TASK_ID='kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T00:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-20T00:05:00+00:00'
[2025-05-20T00:05:01.371+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-20T00:05:01.380+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-20T00:05:01.380+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-20T00:05:01.380+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-20T00:05:01.381+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: connecting to host.docker.internal:9092 [('fdc4:f303:9324::254', 9092, 0, 0) IPv6]
[2025-05-20T00:05:01.381+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Connect attempt returned error 101. Disconnecting.
[2025-05-20T00:05:01.381+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 101 ENETUNREACH
[2025-05-20T00:05:01.381+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.05 secs
[2025-05-20T00:05:01.438+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-20T00:05:01.439+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-20T00:05:01.439+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-20T00:05:01.439+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: connecting to host.docker.internal:9092 [('fdc4:f303:9324::254', 9092, 0, 0) IPv6]
[2025-05-20T00:05:01.439+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Connect attempt returned error 101. Disconnecting.
[2025-05-20T00:05:01.439+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 101 ENETUNREACH
[2025-05-20T00:05:01.440+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.09 secs
[2025-05-20T00:05:01.540+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-20T00:05:01.541+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-20T00:05:01.541+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-20T00:05:01.541+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: connecting to host.docker.internal:9092 [('fdc4:f303:9324::254', 9092, 0, 0) IPv6]
[2025-05-20T00:05:01.542+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Connect attempt returned error 101. Disconnecting.
[2025-05-20T00:05:01.542+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 101 ENETUNREACH
[2025-05-20T00:05:01.542+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.18 secs
[2025-05-20T00:05:01.726+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-20T00:05:01.728+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-20T00:05:01.729+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-20T00:05:01.730+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: connecting to host.docker.internal:9092 [('fdc4:f303:9324::254', 9092, 0, 0) IPv6]
[2025-05-20T00:05:01.730+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Connect attempt returned error 101. Disconnecting.
[2025-05-20T00:05:01.731+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 101 ENETUNREACH
[2025-05-20T00:05:01.732+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.36 secs
[2025-05-20T00:05:02.092+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-20T00:05:02.093+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-20T00:05:02.093+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-20T00:05:02.094+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: connecting to host.docker.internal:9092 [('fdc4:f303:9324::254', 9092, 0, 0) IPv6]
[2025-05-20T00:05:02.094+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Connect attempt returned error 101. Disconnecting.
[2025-05-20T00:05:02.094+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 101 ENETUNREACH
[2025-05-20T00:05:02.094+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.88 secs
[2025-05-20T00:05:02.985+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-20T00:05:02.988+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-05-20T00:05:03.004+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-05-20T00:05:03.005+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: connecting to host.docker.internal:9092 [('fdc4:f303:9324::254', 9092, 0, 0) IPv6]
[2025-05-20T00:05:03.005+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Connect attempt returned error 101. Disconnecting.
[2025-05-20T00:05:03.005+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv6 ('fdc4:f303:9324::254', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 101 ENETUNREACH
[2025-05-20T00:05:03.005+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.37 secs
[2025-05-20T00:05:03.380+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/log_to_csv.py", line 39, in kafka_producer
    producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-05-20T00:05:03.400+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_parquet, task_id=kafka_producer, run_id=scheduled__2025-05-20T00:05:00+00:00, execution_date=20250520T000500, start_date=20250520T000501, end_date=20250520T000503
[2025-05-20T00:05:03.412+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-20T00:05:03.413+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 96 for task kafka_producer (NoBrokersAvailable; 5107)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/log_to_csv.py", line 39, in kafka_producer
    producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-05-20T00:05:03.432+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T00:05:03.447+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T00:05:03.448+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
