[2025-05-19T06:42:57.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T06:42:57.441+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_parquet.kafka_consumer scheduled__2025-05-19T06:02:00+00:00 [queued]>
[2025-05-19T06:42:57.443+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_parquet.kafka_consumer scheduled__2025-05-19T06:02:00+00:00 [queued]>
[2025-05-19T06:42:57.444+0000] {taskinstance.py:2865} INFO - Starting attempt 4 of 5
[2025-05-19T06:42:57.448+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): kafka_consumer> on 2025-05-19 06:02:00+00:00
[2025-05-19T06:42:57.450+0000] {standard_task_runner.py:72} INFO - Started process 434 to run task
[2025-05-19T06:42:57.452+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'csv_to_parquet', 'kafka_consumer', 'scheduled__2025-05-19T06:02:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_parquet.py', '--cfg-path', '/tmp/tmpe1cxtxsv']
[2025-05-19T06:42:57.452+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask kafka_consumer
[2025-05-19T06:42:57.469+0000] {task_command.py:467} INFO - Running <TaskInstance: csv_to_parquet.kafka_consumer scheduled__2025-05-19T06:02:00+00:00 [running]> on host 8b6a4ce3396b
[2025-05-19T06:42:57.568+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_parquet' AIRFLOW_CTX_TASK_ID='kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T06:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T06:02:00+00:00'
[2025-05-19T06:42:57.569+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T06:42:57.575+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-19T06:42:57.577+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <checking_api_versions_recv> [IPv4 ('192.168.65.254', 9092)]>: Broker version identified as 2.6
[2025-05-19T06:42:57.578+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Connection complete.
[2025-05-19T06:42:57.578+0000] {subscription_state.py:177} INFO - Updating subscribed topics to: ('***test',)
[2025-05-19T06:42:57.578+0000] {logging_mixin.py:190} INFO - ✅ Consumer started, waiting for messages...
[2025-05-19T06:42:57.580+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: connecting to 172.16.24.224:9092 [('172.16.24.224', 9092) IPv4]
[2025-05-19T06:42:57.686+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Connection complete.
[2025-05-19T06:42:57.687+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. 
[2025-05-19T06:42:57.795+0000] {cluster.py:400} INFO - Coordinator for group/tt is ('coordinator-1', '172.16.24.224', 9092, None)
[2025-05-19T06:42:57.796+0000] {base.py:769} INFO - Discovered coordinator coordinator-1 for group tt
[2025-05-19T06:42:57.797+0000] {base.py:820} INFO - Starting new heartbeat thread
[2025-05-19T06:42:57.799+0000] {consumer.py:362} INFO - Revoking previously assigned partitions () for group tt
[2025-05-19T06:42:57.800+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1 host=172.16.24.224:9092 <connecting> [IPv4 ('172.16.24.224', 9092)]>: connecting to 172.16.24.224:9092 [('172.16.24.224', 9092) IPv4]
[2025-05-19T06:42:57.905+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Connection complete.
[2025-05-19T06:42:58.008+0000] {base.py:524} INFO - (Re-)joining group tt
[2025-05-19T06:42:58.017+0000] {base.py:524} INFO - (Re-)joining group tt
[2025-05-19T06:43:01.027+0000] {base.py:587} INFO - Elected group leader -- performing partition assignments using range
[2025-05-19T06:43:01.044+0000] {base.py:401} INFO - Successfully joined group tt with generation 1
[2025-05-19T06:43:01.045+0000] {subscription_state.py:246} INFO - Updated partition assignment: [('***test', 0)]
[2025-05-19T06:43:01.046+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('***test', 0),) for group tt
[2025-05-19T06:43:01.052+0000] {fetcher.py:413} INFO - Resetting offset for partition ('***test', 0) to offset 0.
[2025-05-19T06:43:06.079+0000] {logging_mixin.py:190} INFO - No messages received (1/3). Waiting...
[2025-05-19T06:43:13.085+0000] {logging_mixin.py:190} INFO - No messages received (2/3). Waiting...
[2025-05-19T06:43:20.090+0000] {logging_mixin.py:190} INFO - No messages received (3/3). Waiting...
[2025-05-19T06:43:22.096+0000] {logging_mixin.py:190} INFO - ❌ Error in kafka_consumer: local variable 'msg_count' referenced before assignment
[2025-05-19T06:43:22.097+0000] {base.py:834} INFO - Stopping heartbeat thread
[2025-05-19T06:43:25.101+0000] {base.py:1037} WARNING - Heartbeat thread did not fully terminate during close
[2025-05-19T06:43:25.103+0000] {base.py:865} INFO - Leaving consumer group (tt).
[2025-05-19T06:43:25.110+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Closing connection. 
[2025-05-19T06:43:25.112+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1 host=172.16.24.224:9092 <connected> [IPv4 ('172.16.24.224', 9092)]>: Closing connection. 
[2025-05-19T06:43:25.114+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/csv_to_parquet.py", line 120, in kafka_consumer
    if msg_count > 0:
UnboundLocalError: local variable 'msg_count' referenced before assignment
[2025-05-19T06:43:25.131+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_parquet, task_id=kafka_consumer, run_id=scheduled__2025-05-19T06:02:00+00:00, execution_date=20250519T060200, start_date=20250519T064257, end_date=20250519T064325
[2025-05-19T06:43:25.142+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T06:43:25.142+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task kafka_consumer (local variable 'msg_count' referenced before assignment; 434)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/csv_to_parquet.py", line 120, in kafka_consumer
    if msg_count > 0:
UnboundLocalError: local variable 'msg_count' referenced before assignment
[2025-05-19T06:43:25.160+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-19T06:43:25.170+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T06:43:25.171+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
