[2025-05-20T09:33:30.483+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T09:33:30.488+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.check_minio_file scheduled__2025-05-19T16:00:00+00:00 [queued]>
[2025-05-20T09:33:30.491+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.check_minio_file scheduled__2025-05-19T16:00:00+00:00 [queued]>
[2025-05-20T09:33:30.491+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-05-20T09:33:30.495+0000] {taskinstance.py:2888} INFO - Executing <Task(S3KeySensor): check_minio_file> on 2025-05-19 16:00:00+00:00
[2025-05-20T09:33:30.497+0000] {standard_task_runner.py:72} INFO - Started process 669 to run task
[2025-05-20T09:33:30.498+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_minio_to_spark', 'check_minio_file', 'scheduled__2025-05-19T16:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/testlog_ml.py', '--cfg-path', '/tmp/tmp1xo4tntb']
[2025-05-20T09:33:30.499+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask check_minio_file
[2025-05-20T09:33:30.517+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_minio_to_spark.check_minio_file scheduled__2025-05-19T16:00:00+00:00 [running]> on host 6a89a243c286
[2025-05-20T09:33:30.624+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_minio_to_spark' AIRFLOW_CTX_TASK_ID='check_minio_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T16:00:00+00:00'
[2025-05-20T09:33:30.624+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-20T09:33:30.629+0000] {baseoperator.py:405} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2025-05-20T09:33:30.629+0000] {s3.py:118} INFO - Poking for key : s3://user-log-ml/2025-05-20_10-00-00.csv
[2025-05-20T09:33:30.633+0000] {base.py:84} INFO - Retrieving connection 'minio'
[2025-05-20T09:33:30.634+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='minio', conn_type='aws') credentials retrieved from login and password.
[2025-05-20T09:34:30.786+0000] {s3.py:118} INFO - Poking for key : s3://user-log-ml/2025-05-20_10-00-00.csv
[2025-05-20T09:34:56.139+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-20T09:34:56.140+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-20T09:34:56.141+0000] {process_utils.py:132} INFO - Sending 15 to group 669. PIDs of all processes in the group: [669]
[2025-05-20T09:34:56.141+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 669
[2025-05-20T09:34:56.142+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-20T09:34:56.153+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-20T09:34:56.174+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=669, status='terminated', exitcode=0, started='09:33:29') (669) terminated with exit code 0
